### ISSUE TITLE
Phone Number Issue

### ISSUE THREAD

**Issue by Haque197** [Haque197/Web-Scraper-for-Dubizzle#2]
I am unable to scrape the Phone Number, I used various for loops but it did not work as it kept coming up as square brackets, the website is https://dubai.dubizzle.com/en/property-for-sale/residential/?filters=(listed_by.value%3A%22LA%22).

Please use inspect element on the website in order to find the HTML tags where the number is stored.

**Comment by zrahman001** [comment]
You will struggle to do this with Beautiful Soup. It cannot click into links for you. It can only scrape from the HTML that it gets from a URL request. The click event is being handled by Javascript to fetch more data (includes phone number) and then inject into the existing DOM.

You need to use a more advanced module to simulate the click event. Look into using this instead - https://selenium-python.readthedocs.io/

**Comment by Haque197** [comment]
Thanks I’ll look into it

**Comment by Haque197** [comment]
Thank you zrahman001 for your assistance!
